import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  BookOpen,
  Box,
  Calendar,
  Check,
  CheckCircle2,
  ChevronRight,
  Clock,
  Compass,
  Cookie,
  CreditCard,
  Eye,
  FileText,
  Flame,
  Gift,
  Globe,
  Headset,
  Heart,
  HelpCircle,
  Home,
  Info,
  Instagram,
  LayoutGrid,
  Leaf,
  LifeBuoy,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Package,
  PenLine,
  Percent,
  Phone,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Share2,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Tag,
  Truck,
  User,
  Users,
  Wallet,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/**
 * Icon registry for CMS-authored icon names. Admins type a name (e.g.
 * "ShoppingBag") in the admin panel and it renders here. Unknown or empty
 * names render nothing so a typo never breaks a page.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  BookOpen,
  Box,
  Calendar,
  Check,
  CheckCircle2,
  ChevronRight,
  Clock,
  Compass,
  Cookie,
  CreditCard,
  Eye,
  FileText,
  Flame,
  Gift,
  Globe,
  Headset,
  Heart,
  HelpCircle,
  Home,
  Info,
  Instagram,
  LayoutGrid,
  Leaf,
  LifeBuoy,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Package,
  PenLine,
  Percent,
  Phone,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Share2,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Tag,
  Truck,
  User,
  Users,
  Wallet,
  Zap,
};

export const ICON_NAMES = Object.keys(ICON_MAP).sort();

export function CmsIcon({ name, className }: { name?: string | null; className?: string }) {
  if (!name) return null;
  const Icon = ICON_MAP[name] ?? ICON_MAP[name.charAt(0).toUpperCase() + name.slice(1)];
  if (!Icon) return null;
  return <Icon className={className ?? "size-4"} aria-hidden />;
}
